---

- name: Admin | Create root group
  group:
    name: root
    system: true
    gid: 0
  tags:
    - accounts

- name: Admin | Create root user
  user:
    name: root
    system: true
    comment: "Root User"
    uid: 0
    group: root
    password: '{{ root_password_hash }}'
  tags:
    - accounts

- name: Admin | set roots mail alias
  lineinfile:
    dest: /etc/aliases
    line: "{{ item.name }}: {{ item.alias }}"
    regexp: "^{{ item.name }}:.*"
  with_items:
    - '{{ mailaliases }}'
  notify: update aliases database

- name: Admin | Create sshusers group
  group:
    name: sshusers
    system: true
    gid: 500
  tags:
    - accounts

- name: Admin | Create admin group
  group:
    name: admin
    system: true
    gid: 1000
    state: present
  tags:
    - accounts

- name: Admin | Create admin user
  user:
    name: admin
    system: true
    comment: "Admin User"
    uid: 1000
    group: admin
    groups: [ wheel, sshusers ]
    password: '{{ admin_password_hash }}'
  tags:
    - accounts

- name: Admin | Set admin users authorized key
  authorized_key:
    user: admin
    state: present
    comment: '{{ item.comment }}'
    key: '{{ item.key }}'
  with_items:
    - '{{ admin_ssh_keys }}'
  tags:
    - accounts
