# Ensure host is present
- ipa_host:
  name: host01.example.com
  description: Example host
  ip_address: 192.168.0.123
  ns_host_location: Lab
  ns_os_version: CentOS 7
  ns_hardware_platform: Lenovo T61
  mac_address:
  - "08:00:27:E3:B1:2D"
  - "52:54:00:BD:97:1E"
  state: present
  ipa_host: ipa.example.com
  ipa_user: admin
  ipa_pass: topsecret
