---

- name: Install packages
  yum:
    name: parted
    state: present

- name: Get info
  parted:
    device: "{{dev}}"
    number: "{{part}}"
  register: partinfo
- set_fact:
    gap_kb: "{{partinfo.disk.size - partinfo.partitions[vars.part-1].end}}"
- debug: 'msg="Gap after partition {{part}}: {{gap_kb}}kiB"'
# parted does not resize: https://github.com/ansible/ansible/issues/23914
- name: grow too small partition to maximum
  # Request resize, ack resize of partition that is in use (when requested).
  # https://bugs.launchpad.net/ubuntu/+source/parted/+bug/1270203
  # https://unix.stackexchange.com/a/365657
  command: 'parted --pretend-input-tty {{dev}} resizepart {{part}} Yes 100%'
  when: max_gap_kb < gap_kb|int
